#P
service.ProcessEntity.create=banfftech.createProcessEntity
service.ProcessEntity.update=banfftech.updateProcessEntity
service.ProcessField.create=banfftech.createProcessField
service.ProcessField.update=banfftech.updateProcessField

service.MainProcess.create=banfftech.createMainProcess
service.MainProcess.update=banfftech.updateMainProcess

#PartyAndPartyGroup
service.PartyAndPartyGroup.create=banfftech.createPartyAndPartyGroup
service.PartyAndPartyGroup.update=banfftech.updatePartyAndPartyGroup
service.PartyAndPartyGroup.delete=banfftech.deletePartyAndPartyGroup

#Department
service.Department.create=banfftech.createDepartment
#UserGroup
service.UserGroup.create=banfftech.createUserGroup
#PartyRelationship
service.PartyRelationship.create=banfftech.createPartyRelationship
service.PartyRelationship.update=banfftech.updatePartyRelationshipAndCheckRole
service.PartyRelationship.delete=banfftech.deletePartyRelationship

#PartyAndContact
service.PartyAndContact.create=banfftech.createPartyAndContact
service.PartyAndContact.update=banfftech.updatePartyAndContact
service.PartyAndContact.delete=banfftech.deletePartyAndContact

#Person
service.Person.create=banfftech.createPerson
service.Person.update=banfftech.updatePerson
service.Person.delete=banfftech.deletePerson

#RoleType
service.RoleType.create=banfftech.createRoleType
service.RoleType.update=banfftech.updateRoleType
service.RoleType.delete=banfftech.deleteRoleType

#PartyRole
service.PartyRole.create=banfftech.createPartyRole
service.PartyRole.update=banfftech.updatePartyRole
service.PartyRole.delete=banfftech.deletePartyRole

#UserLogin
service.UserLogin.create=banfftech.createUserLogin
service.UserLogin.update=banfftech.updateUserLogin
service.UserLogin.delete=banfftech.deleteUserLogin

#EmplLeave
service.EmplLeave.create=banfftech.createEmplLeave
service.EmplLeave.update=banfftech.updateEmplLeave
service.EmplLeave.delete=banfftech.deleteEmplLeave


#Requirement
service.Requirement.create=banfftech.createRequirement
service.Requirement.update=banfftech.updateRequirement
service.Requirement.delete=banfftech.deleteRequirement

#RequirementAttribute
service.RequirementAttribute.create=banfftech.createRequirementAttribute
service.RequirementAttribute.update=banfftech.updateRequirementAttribute
service.RequirementAttribute.delete=banfftech.deleteRequirementAttribute

#Product
service.Product.create=banfftech.createProduct
service.Product.update=banfftech.updateProduct
service.Product.delete=banfftech.deleteProduct

#ProductAttribute
service.ProductAttribute.create=banfftech.createProductAttribute
service.ProductAttribute.update=banfftech.updateProductAttribute

#FixedAsset
service.FixedAsset.create=banfftech.createFixedAsset
service.FixedAsset.update=banfftech.updateFixedAsset

#FixedAssetAttribute
service.FixedAssetAttribute.create=banfftech.createFixedAssetAttribute
service.FixedAssetAttribute.update=banfftech.updateFixedAssetAttribute

#FixedAssetAttributeDate
service.FixedAssetAttributeDate.create=banfftech.createFixedAssetAttributeDate
service.FixedAssetAttributeDate.update=banfftech.updateFixedAssetAttributeDate