#P
service.ProcessEntity.create=banfftech.createProcessEntity
service.ProcessEntity.update=banfftech.updateProcessEntity

service.MainProcess.create=banfftech.createMainProcess
service.MainProcess.update=banfftech.updateMainProcess

#PartyAndPartyGroup
service.PartyAndPartyGroup.create=banfftech.createPartyAndPartyGroup
service.PartyAndPartyGroup.update=banfftech.updatePartyAndPartyGroup
service.PartyAndPartyGroup.delete=banfftech.deletePartyAndPartyGroup

#Department
service.Department.create=banfftech.createDepartment

#PartyRelationship
service.PartyRelationship.create=banfftech.createPartyRelationship
service.PartyRelationship.update=banfftech.updatePartyRelationshipAndCheckRole
service.PartyRelationship.delete=banfftech.deletePartyRelationship

#PartyAndContact
service.PartyAndContact.create=banfftech.createPartyAndContact
service.PartyAndContact.update=banfftech.updatePartyAndContact
service.PartyAndContact.delete=banfftech.deletePartyAndContact

#Person
service.Person.create=banfftech.createPerson
service.Person.update=banfftech.updatePerson
service.Person.delete=banfftech.deletePerson

#RoleType
service.RoleType.create=banfftech.createRoleType
service.RoleType.update=banfftech.updateRoleType
service.RoleType.delete=banfftech.deleteRoleType

#PartyRole
service.PartyRole.create=banfftech.createPartyRole
service.PartyRole.update=banfftech.updatePartyRole
service.PartyRole.delete=banfftech.deletePartyRole

#UserLogin
serviceUserLogin.create=banfftech.createUserLogin
serviceUserLogin.update=banfftech.updateUserLogin
serviceUserLogin.delete=banfftech.deleteUserLogin

