#P
service.ProcessEntity.create=banfftech.createProcessEntity
service.ProcessEntity.update=banfftech.updateProcessEntity

#PartyAndPartyGroup
service.PartyAndPartyGroup.create=banfftech.createPartyAndPartyGroup
service.PartyAndPartyGroup.update=banfftech.updatePartyAndPartyGroup
service.PartyAndPartyGroup.delete=banfftech.deletePartyAndPartyGroup

#PartyRelationship
service.PartyRelationship.create=banfftech.createPartyRelationship
service.PartyRelationship.update=banfftech.updatePartyRelationship
service.PartyRelationship.delete=banfftech.deletePartyRelationship